const { AgentMailClient } = require('agentmail');
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Base directory for the double-agent project
const PROJECT_ROOT = path.join(__dirname, '..');

// Load .env manually
function loadEnv() {
  const envPath = path.join(PROJECT_ROOT, '.env');
  if (fs.existsSync(envPath)) {
    const envContent = fs.readFileSync(envPath, 'utf-8');
    const lines = envContent.split('\n');
    lines.forEach(line => {
      const match = line.match(/^([^=]+)=(.*)$/);
      if (match) {
        process.env[match[1]] = match[2];
      }
    });
  }
}
loadEnv();

async function checkInbox() {
  const apiKey = process.env.AGENTMAIL_API_KEY;
  const inboxId = process.env.AGENT_EMAIL_ADDRESS || 'repulsivemeaning51@agentmail.to';

  if (!apiKey) {
    console.error('AGENTMAIL_API_KEY not found in environment');
    process.exit(1);
  }

  try {
    const client = new AgentMailClient({ apiKey });

    console.log(`Fetching messages for inbox: ${inboxId}`);
    const response = await client.inboxes.messages.list(inboxId, { limit: 50 });
    const messages = response.messages || [];

    // Generate filename with timestamp
    const now = new Date();
    const timestamp = now.toISOString().replace(/[-:]/g, '').split('.')[0];
    const filename = `check-${timestamp}.md`;
    const dir = path.join(PROJECT_ROOT, 'inbox');

    // Ensure inbox directory exists
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    const filepath = path.join(dir, filename);

    // Build report content
    let report = `# Email Inbox Check Report\n\n`;
    report += `**Timestamp:** ${now.toLocaleString('en-US', { timeZone: 'Asia/Tokyo' })} (Asia/Tokyo)\n`;
    report += `**Inbox:** ${inboxId}\n`;
    report += `**Total Messages:** ${messages.length}\n\n`;

    if (messages.length === 0) {
      report += `## No Messages\n\n`;
      report += `No messages found in the inbox at this time.\n`;
    } else {
      report += `## Messages\n\n`;

      // Identify urgent keywords
      const urgentKeywords = ['urgent', 'asap', 'response needed', 'immediate', 'time-sensitive', 'critical'];

      messages.forEach((msg, idx) => {
        const sender = msg.from || 'Unknown';
        const subject = msg.subject || '(No Subject)';
        const date = msg.timestamp ? new Date(msg.timestamp).toLocaleString() : 'Unknown';
        const snippet = msg.preview?.substring(0, 150) || '(No preview)';

        // Check for urgency
        const content = (subject + ' ' + snippet).toLowerCase();
        const isUrgent = urgentKeywords.some(keyword => content.includes(keyword));

        report += `### ${idx + 1}. ${subject}\n\n`;
        report += `- **From:** ${sender}\n`;
        report += `- **Date:** ${date}\n`;
        report += `- **Snippet:** ${snippet}\n`;
        if (isUrgent) {
          report += `- **⚠️ Urgent:** This message contains urgent keywords\n`;
        }
        report += `\n`;
      });

      // Summary of urgent items
      const urgentMessages = messages.filter(msg => {
        const content = ((msg.subject || '') + ' ' + (msg.preview?.substring(0, 150) || '')).toLowerCase();
        return urgentKeywords.some(k => content.includes(k));
      });

      if (urgentMessages.length > 0) {
        report += `## ⚠️ Urgent Items\n\n`;
        urgentMessages.forEach((msg, idx) => {
          report += `${idx + 1}. **${msg.subject || '(No Subject)'}** from ${msg.from}\n`;
        });
        report += `\n`;
        report += `**Recommended Actions:** Review urgent messages promptly.\n\n`;
      }
    }

    report += `---\n*Generated by Double Agent email automation*\n`;

    fs.writeFileSync(filepath, report, 'utf-8');
    console.log(`Report saved to: ${filepath}`);
    console.log(`Total messages found: ${messages.length}`);

    // Git commit - run from project root
    const today = now.toISOString().split('T')[0];
    const commitMsg = `chore: email check report ${today}`;
    console.log(`Committing with message: "${commitMsg}"`);

    try {
      // Use absolute path and run from project root
      execSync(`git add ${filepath}`, { stdio: 'inherit', cwd: PROJECT_ROOT });
      execSync(`git commit -m "${commitMsg}"`, { stdio: 'inherit', cwd: PROJECT_ROOT });
      console.log('Commit successful');
    } catch (err) {
      console.error('Git commit failed:', err.message);
    }

    return messages.length;
  } catch (error) {
    console.error('Error checking inbox:', error);
    if (error.statusCode) {
      console.error('Status code:', error.statusCode);
    }
    process.exit(1);
  }
}

checkInbox();
